extend type Mutation {
    createRole(input: CreateRoleInput): Role!
        @inject(context: "user.client_id", name: "input.client_id")

    updateRole(input: UpdateRoleInput): Role!
        @inject(context: "user.client_id", name: "input.client_id")
}
