type Team {
    id: ID!
    name: String
    home_team: Boolean
    created_at: DateTime
    updated_at: DateTime
    users: [User]! @hasMany
    user: TeamUser @hasMany
    locations: [Location] @hasMany
}

type TeamUser {
    user: User @belongsTo
}
