version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  enabled: true
  config:
    standard: ".quality/phpcs.xml"
