<?php

namespace App\Domain\Templates\SmsTemplates;

use App\Domain\Templates\SmsTemplates\Events\SmsTemplateCreated;
use App\Domain\Templates\SmsTemplates\Events\SmsTemplateDeleted;
use App\Domain\Templates\SmsTemplates\Events\SmsTemplateRestored;
use App\Domain\Templates\SmsTemplates\Events\SmsTemplateTrashed;
use App\Domain\Templates\SmsTemplates\Events\SmsTemplateUpdated;
use App\Domain\Templates\SmsTemplates\Projections\SmsTemplate;
use App\Domain\Templates\SmsTemplates\Projections\SmsTemplateDetails;
use App\Domain\Users\Models\User;
use Illuminate\Support\Facades\DB;
use Spatie\EventSourcing\EventHandlers\Projectors\Projector;

class SmsTemplateProjector extends Projector
{
    public function onSmsTemplateCreated(SmsTemplateCreated $event)
    {
        DB::transaction(function () use ($event) {
            $template_data = array_filter($event->payload, function ($key) {
                return in_array($key, (new SmsTemplate())->getFillable());
            }, ARRAY_FILTER_USE_KEY);

            $template_data['created_by_user_id'] = $event->modifiedBy();
            $template_data['active'] = 0;//TODO: do we really need to set template to inactive? prob only campaign

            $template = new SmsTemplate();
            $template->fill($template_data);
            $template->id = $event->aggregateRootUuid();
            $template->client_id = $event->clientId();
            $template->writeable()->save();

            $msg = 'Template was auto-generated';
            if (! $event->autoGenerated()) {
                $user = User::find($event->userId());
                $msg = 'Template was created by ' . $user->name . ' on ' . $event->createdAt()->format('Y-m-d');
            }
            SmsTemplateDetails::createOrUpdateRecord($event->aggregateRootUuid(), 'created', $event->createdAt(), ['msg' => $msg]);
        });
    }

    public function onSmsTemplateUpdated(SmsTemplateUpdated $event)
    {
        DB::transaction(function () use ($event) {
            SmsTemplate::findOrFail($event->aggregateRootUuid())->writeable()->updateOrFail($event->payload);
            $user = User::find($event->userId());
            $msg = 'Template was updated by ' . $user->name . ' on ' . $event->createdAt()->format('Y-m-d');
            SmsTemplateDetails::createOrUpdateRecord($event->aggregateRootUuid(), 'updated', $event->modifiedBy(), ['msg' => $msg]);
        });
    }

    public function onSmsTemplateTrashed(SmsTemplateTrashed $event): void
    {
        DB::transaction(function () use ($event) {
            SmsTemplate::withTrashed()->findOrFail($event->aggregateRootUuid())->writeable()->delete();
            SmsTemplateDetails::withTrashed()->whereSmsTemplateId($event->aggregateRootUuid())->delete();
        });
    }

    public function onSmsTemplateRestored(SmsTemplateRestored $event): void
    {
        DB::transaction(function () use ($event) {
            SmsTemplate::withTrashed()->findOrFail($event->aggregateRootUuid())->writeable()->restore();
            SmsTemplateDetails::withTrashed()->whereSmsTemplateId($event->aggregateRootUuid())->restore();
        });
    }

    public function onSmsTemplateDeleted(SmsTemplateDeleted $event): void
    {
        DB::transaction(function () use ($event) {
            SmsTemplate::withTrashed()->findOrFail($event->aggregateRootUuid())->writeable()->forceDelete();
            SmsTemplateDetails::withTrashed()->whereSmsTemplateId($event->aggregateRootUuid())->forceDelete();
        });
    }
}
