type Location {
    id: ID!
    gymrevenue_id: String
    location_no: String
    location_type: String
    name: String
    city: String
    state: String
    active: Boolean
    zip: String
    address1: String
    address2: String
    phone: String
    open_date: DateTime
    close_date: DateTime
    details: [LocationDetails] @hasMany
    client: Client @belongsTo
}

type LocationDetails{
    id: ID
    field: String
    value: String
}
