<?php

declare(strict_types=1);

namespace App\Domain\Users\Models;

use App\Scopes\ClientScope;

class Lead extends EndUser
{
    protected $appends = ['owner'];

    protected static function booted(): void
    {
        parent::booted();
        static::addGlobalScope(new ClientScope());
    }

    public function scopeFilter($query, array $filters): void
    {
        /** @TODO: Change the autogenerated stub */
        parent::scopeFilter($query, $filters);
        $query->when($filters['typeoflead'] ?? null, function ($query, $typeoflead) {
            $query->whereIn('lead_type_id',  $typeoflead);
            /* Filter for Location(s) */
        })->when($filters['grlocation'] ?? null, function ($query, $grlocation) {
            $query->whereIn('home_location_id',  $grlocation);
            /* Filter for EndUser Sources */
        })->when($filters['entrysource'] ?? null, function ($query, $entry_source) {
            $query->whereIn('entry_source_id', $entry_source);
            /* Filter for EndUser Sources */
        });
    }

    public function getPhoneNumber(): string
    {
        return $this->phone;
    }
}
