<?php

declare(strict_types=1);

namespace App\Domain\Users\Models;

use App\Scopes\ClientScope;
use Illuminate\Database\Eloquent\Builder;

class Lead extends EndUser
{
    /** @var array<string>  */
    protected $appends = ['owner'];

    /**
     * @param array<string, mixed> $filters
     *
     */
    public function scopeFilter(Builder $query, array $filters): void
    {
        /** @TODO: Change the autogenerated stub */
        parent::scopeFilter($query, $filters);
        $query->when($filters['typeoflead'] ?? null, function ($query, $typeoflead): void {
            $query->whereIn('lead_type_id', $typeoflead);
            /* Filter for Location(s) */
        })->when($filters['grlocation'] ?? null, function ($query, $grlocation): void {
            $query->whereIn('home_location_id', $grlocation);
            /* Filter for EndUser Sources */
        })->when($filters['entrysource'] ?? null, function ($query, $entry_source): void {
            $query->whereIn('entry_source_id', $entry_source);
            /* Filter for EndUser Sources */
        });
    }

    public function getPhoneNumber(): string
    {
        return $this->phone;
    }

    protected static function booted(): void
    {
        parent::booted();
        static::addGlobalScope(new ClientScope());
    }
}
