extend type Query {
    departments(
        "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
        name: String @where(operator: "like")
    ): [Department!]!
    @orderBy(column: "name")
    @paginate(defaultCount: 10)
        @can(ability: "departments.read", model: "App\\Domain\\Departments\\Department")
}