# Queries Email Templates
extend type Query {
    "Queries Email Templates according to optional input filters"
    emailTemplates(
        filter: Filter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [EmailTemplate!]! @paginate(defaultCount: 10)
}

extend type Query {
    "Find a single SMS Template by an identifying attribute."
    emailTemplate(id: ID @eq): EmailTemplate @find
}
