extend type Query {
    leads(filter: LeadsInput @scope): [Lead!]!
    @paginate(defaultCount: 10)
        @can(ability: "leads.read", model: "App\\Domain\\EndUsers\\Leads\\Projections\\Lead")
}

input LeadsInput {
    nameSearch: String
}