extend type Query {
    members(
        filter: Filter @scope
    ): [Member!]!
    @orderBy(column: "first_name")
    @paginate(defaultCount: 10)
        @can(ability: "members.read", model: "App\\Domain\\EndUsers\\Members\\Projections\\Member")
}