extend type Query {
    notes(
        filter: Filter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [Note!]!
    @paginate(defaultCount: 10)

    note(
        id: ID @eq 
    ): Note @find
}