extend type Query {
    positions(
        "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
        filter: PositionFilter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [Position!]!
    @paginate(defaultCount: 10)
        @can(ability: "positions.read", model: "App\\Models\\Position")
}


input PositionFilter {
    search: String
    trashed: String
    state: String
}
