extend type Query {
    reminders(
        "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
        filter: Filter @scope
    ): [Reminder!]!
    @orderBy(column: "name")
    @paginate(defaultCount: 10)
}