extend type Query {
    reminders(
        "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
        filter: Filter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [Reminder!]!
    @paginate(defaultCount: 10)
}