extend type Query {
    tasks(
        "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
        title: String @where(operator: "like")
        orderBy: [OrderByClause!] @orderBy
  ): [CalendarEvent!]!
    @paginate(defaultCount: 10)
}