extend type Query {
    incomplete_tasks(
        incomplete: TaskFilter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [CalendarEvent!]!
    @paginate(defaultCount: 10)

    completed_tasks(
        complete: TaskFilter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [CalendarEvent!]!
    @paginate(defaultCount: 10)

    overdue_tasks(
        overdue: TaskFilter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [CalendarEvent!]!
    @paginate(defaultCount: 10)
}

input TaskFilter {
    start: DateTime
}