<?php

namespace App\StorableEvents;

use App\Models\User;
use Spatie\EventSourcing\StoredEvents\ShouldBeStored;

abstract class GymRevShouldBeStored extends ShouldBeStored
{
    //TODO: use enums for the metadata keys
    public function autoGenerated(): bool
    {
//        return $this->metaData[MetaData::STORED_EVENT_ID] ?? null;
        return $this->metaData['auto-generated'] ?? false;
    }

    public function userId(): ?int
    {
        return $this->metaData['user_id'] ?? null;
    }

    public function accessToken(): ?string
    {
        return $this->metaData['access_token'] ?? null;
    }

    public function ipAddress(): ?string
    {
        return $this->metaData['ip-address'] ?? null;
    }

    public function user(): ?User
    {
        $userId = $this->userId();
        if (! $userId) {
            return null;
        }

        return User::withoutGlobalScopes()->find($userId);
    }

    public function apiUser()
    {
        $accessToken = $this->accessToken();
        if (! $accessToken) {
            return null;
        }

        return User::withoutGlobalScopes()->whereAccessToken($accessToken)->first();
    }
}
