extend type Mutation {
    "Creates a Drip Campaign"
    createDripCampaign(campaign: CreateDripCampaignInput): DripCampaign

    "Updates a Drip Campaign"
    updateDripCampaign(campaign: UpdateDripCampaignInput): DripCampaign
}
