type Customer {
    id: ID!
    first_name: String
    last_name: String
    middle_name: String
    email: String
    phone: String
    alternate_phone: String
    address1: String
    zip: String
    city: String
    state: String
    gender: String
    date_of_birth: DateTime
    created_at: DateTime!
    updated_at: DateTime!
    gr_location_id: ID
    interaction_count: InteractionCount! @method(name: "getInteractionCount")
    home_location: Location! @belongsTo
    locations: [Location] @belongsToMany
    user_type: String
    agreement_number: String
    external_id: String
    misc: String
    notes: [Note] @hasMany
    client: Client @hasOne
}
