"Leads"
type Lead @model(class: "Lead") {
    id: ID!
    name: String!
    first_name: String
    middle_name: String
    last_name: String
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
    #    leadSource: LeadSource @belongsTo
    #    leadType: LeadType @belongsTo
    #    lead_status: LeadStatus
    #    TODO: replace with relationship
    lead_owners: [TeamUser] @method(name: "getTeamUsers")
    owner_user_id: String
    primary_phone: String
    alternate_phone: String
    gender: Boolean
    date_of_birth: DateTime
    interaction_count: InteractionCount! @method(name: "getInteractionCount")
    home_location: Location @belongsTo
    locations: [Location] @belongsToMany
    opportunity: String
    agreement_number: String
    misc: String
    external_id: String
    lead_status_id: String
    owner_user_id: String
    notes: [Note] @hasMany
    gr_location_id: ID
    user_type: String
}
