type Member {
    id: ID!
    first_name: String
    last_name: String
    middle_name: String
    email: String
    primary_phone: String
    alternate_phone: String
    gender: String
    date_of_birth: DateTime!
    created_at: DateTime!
    updated_at: DateTime!
    location: Location!
    gr_location_id: ID
    interaction_count: InteractionCount! @method(name: "getInteractionCount")
    preview_note: [String]! @method(name: "getPreviewNote")
    club_location: Location @method(name: "getClubLocation")
    locations: [Location] @method(name: "getLocations")
    agreement_number: String
    external_id: String
    misc: String
    all_notes: String
    notes: [Note] @hasMany
    client: Client @hasOne
}
