type Member {
    id: ID!
    first_name: String
    last_name: String
    middle_name: String
    email: String
    primary_phone: String
    alternate_phone: String
    gender: String
    date_of_birth: DateTime
    created_at: DateTime
    updated_at: DateTime
    gr_location_id: ID
    interaction_count: InteractionCount @method(name: "getInteractionCount")
    home_location: Location @belongsTo
    locations: [Location] @belongsToMany
    agreement_number: String
    external_id: String
    misc: String
    notes: [Note] @hasMany
}
