"Account of a person who utilizes this application."
type User {
    id: ID!
    name: String!
    first_name: String
    last_name: String
    email: String!
    alternate_email: String
    address1: String
    address2: String
    email_verified_at: DateTime
    created_at: DateTime!
    updated_at: DateTime!
    start_date: DateTime
    end_date: DateTime
    termination_date: DateTime
    manager: String
    zip: String
    defaultTeam: Team @hasOne
    role: String
    phone: String
    city: String
    state: String
    home_location: Location @belongsTo
    teams: [Team] @belongsToMany
    contact_preference: ContactPreference @hasOne
    emergency_contact: EmergencyContact
    departments: [Department] @belongsToMany
    positions: [Position] @belongsToMany
    isClientUser: Boolean @method(name: "isClientUser")
}

type EmergencyContact {
    ec_first_name: String
    ec_last_name: String
    ec_phone: String
}
