input UserInput @validator {
    id: ID
    first_name: String
    last_name: String
    email: String
    alternate_email: String
    address1: String
    address2: String
    phone: String
    city: String
    state: String
    zip: String
    contact_preference: String
    start_date: String
    end_date: String
    termination_date: String
    notes: NoteInput
    team_id: ID
    role_id: ID
    home_location_id: ID
    manager: String
    departments: [ID]
    positions: [ID]
}
input NoteInput @validator {
    note: String
    title: String
}

input CustomerInput {
    id: ID
    email: String
    first_name: String
    last_name: String
    phone: String
    user_type: String
    gender: String
    date_of_birth: DateTime
    address1: String
    zip: String
    city: String
    state: String
}
