extend type Mutation {
    "Creates a EmailTemplate"
    createEmailTemplate(
        emailTemplate: CreateEmailTemplateInput!
    ): EmailTemplate!
        @inject(context: "user.client_id", name: "location.client_id")
}

extend type Mutation {
    updateEmailTemplate(
        emailTemplate: UpdateEmailTemplateInput!
    ): EmailTemplate!
        @inject(context: "user.client_id", name: "location.client_id")
}
