# Create Input for EmailTemplates
input CreateEmailTemplateInput {
    name: String! @rules(apply: ["required", "string", "max:50"], attribute: "Name")
    subject: String! @rules(apply: ["required", "string"], attribute: "Subject")
    markup: String! @rules(apply: ["required", "string"], attribute: "Markup")
    json: String! @rules(apply: ["required", "string"], attribute: "Json")
}
