extend type Mutation {
    createPosition(input: CreatePositionInput @spread): Position!
        @inject(context: "user.client_id", name: "client_id")

    updatePosition(input: UpdatePositionInput @spread): Position!
        @inject(context: "user.client_id", name: "client_id")
}
