input PositionFilter {
    search: String
    trashed: String
    state: String
}

input CreatePositionInput @validator {
    name: String
    departments: [ID]
}

input UpdatePositionInput @validator {
    id: ID
    name: String
    departments: [ID]
}
