extend type Query {
    audiences(
        filter: Filter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [Audience!]! @paginate(defaultCount: 10)
}

extend type Query {
    audience(id: ID @eq): Audience @find
}
