type Audience {
    id: ID
    client_id: ID
    name: String
    filters: AudienceTargets
    created_at: DateTime
    deleted_at: DateTime
    updated_at: DateTime
    editable: Int
    entity: String
}

type AudienceTargets {
    lead_type_id: [ID]
    membership_type_id: [ID]
}
