<?php

namespace App\Domain\Templates\EmailTemplates;

use App\Domain\Templates\EmailTemplates\Events\EmailTemplateCreated;
use App\Domain\Templates\EmailTemplates\Events\EmailTemplateDeleted;
use App\Domain\Templates\EmailTemplates\Events\EmailTemplateRestored;
use App\Domain\Templates\EmailTemplates\Events\EmailTemplateThumbnailUpdated;
use App\Domain\Templates\EmailTemplates\Events\EmailTemplateTrashed;
use App\Domain\Templates\EmailTemplates\Events\EmailTemplateUpdated;
use App\Domain\Templates\EmailTemplates\Projections\EmailTemplate;
use App\Domain\Users\Models\User;
use Illuminate\Support\Facades\DB;
use Spatie\EventSourcing\EventHandlers\Projectors\Projector;

class EmailTemplateProjector extends Projector
{
    public function onStartingEventReplay()
    {
        EmailTemplate::truncate();
    }

    public function onEmailTemplateCreated(EmailTemplateCreated $event)
    {
        DB::transaction(function () use ($event) {
            $template_data = array_filter($event->payload, function ($key) {
                return in_array($key, (new EmailTemplate())->getFillable());
            }, ARRAY_FILTER_USE_KEY);

            $msg = 'Template was auto-generated';
            if (! $event->autoGenerated()) {
                $user = User::find($event->userId());
                $msg = 'Template was created by ' . $user->name . ' on ' . $event->createdAt()->format('Y-m-d');
            }

            $template_data['created_by_user_id'] = $event->modifiedBy();
            $template_data['active'] = 0;//TODO: do we really need to set template to inactive? prob only campaign

            $template = new EmailTemplate();
            $template->id = $event->aggregateRootUuid();
            $template->client_id = $event->clientId();
            $template->fill($template_data);
            $template->details = ['created' => $msg];
            $template->writeable()->save();
        });
    }

    public function onEmailTemplateUpdated(EmailTemplateUpdated $event)
    {
        DB::transaction(function () use ($event) {
            $template = EmailTemplate::findOrFail($event->aggregateRootUuid());

            $payload = $event->payload;

            if (! $event->autoGenerated()) {
                $user = User::find($event->modifiedBy());
                $msg = 'Template was updated by ' . $user->name . ' on ' . $event->createdAt()->format('Y-m-d');

                $payload['details'] = $template->details ?? [];
                $payload['details']['updated'] = $msg;
            }

            $template->writeable()->updateOrFail($payload);
        });
    }

    public function onEmailTemplateTrashed(EmailTemplateTrashed $event): void
    {
        DB::transaction(function () use ($event) {
            EmailTemplate::withTrashed()->findOrFail($event->aggregateRootUuid())->writeable()->delete();
        });
    }

    public function onEmailTemplateRestored(EmailTemplateRestored $event): void
    {
        DB::transaction(function () use ($data, $event) {
            EmailTemplate::withTrashed()->findOrFail($event->aggregateRootUuid())->writeable()->restore();
        });
    }

    public function onEmailTemplateDeleted(EmailTemplateDeleted $event): void
    {
        DB::transaction(function () use ($event) {
            EmailTemplate::withTrashed()->findOrFail($event->aggregateRootUuid())->writeable()->forceDelete();
        });
    }

    public function onEmailTemplateThumbnailUpdated(EmailTemplateThumbnailUpdated $event)
    {
        EmailTemplate::findOrFail($event->aggregateRootUuid())->writeable()->updateOrFail(['thumbnail' => ['key' => $event->key, 'url' => $event->url]]);
    }
}
