type CalendarEvent {
    id: ID!
    title: String!
    description: String
    full_day_event: Int
    event_type_id: ID
    client_id: ID
    owner: User!
    owner_id: ID
    start: DateTime
    end: DateTime
    created_at: DateTime
    event_completion: DateTime

    editable: Int
    full_day_event: Int
    type: CalendarEventType
    user_attendees: [EventAttendee]
    lead_attendees: [EventAttendee]
    member_attendees: [EventAttendee]
    attendees: [EventAttendeeDetail]
    location_id: ID
    call_task: Int
    im_attending: Boolean
    my_reminder: Reminder
}

type CalendarEventType {
    id: ID!
    name: String!
    description: String
    color: String
    type: String
    created_at: DateTime
    updated_at: DateTime
    client: Client @belongsTo
}

type EventAttendee {
    id: ID
}

type EventAttendeeDetail {
    id: ID
    entity_type: String
    invitation_status: String
    entity_data: AttendeeDetailData
}
type AttendeeDetailData {
    profile_photo_url: String
    name: String
    first_name: String
    last_name: String
    email: String
}