extend type Query {
    folders(
        filter: Filter @scope
        orderBy: [OrderByClause!] @orderBy
    ): [Folder!]! @all

    folderContent(
        id: ID,
        filter: Filter
    ): FolderContent

    folder(
        id: ID @eq
    ): Folder @find
}
